repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    wait: true
    chart: jetstack/cert-manager
    version: 1.14.5
    values:
      - values-cert-manager.yaml.gotmpl
    # deploy custom resource using hooks feature of helmfile since there is nothing like extraDeploy for this chart
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./cert-manager-cluster-issuer.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"

  # - name: ingress-nginx
  #   labels:
  #     app: ingress-nginx
  #   wait: true
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.10.1
  #   values:
  #     - values-ingress-nginx.yaml.gotmpl
